server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: org.atguigu.com.atguigu.springcloud.entities
  mapper-locations:
    - classpath:com/atguigu/com.atguigu.springcloud/dao/mapper/*.xml

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_test?useSSL=false&serverTimezone=UTC
    username: root
    password: crscd123@
    # 使用druid数据源
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

logging:
  level:
    com.atguigu.springcloud.dao: debug

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8002
    prefer-ip-address: true

info:
  app.name: atguigu.microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.verson: $project.version$